+incdir+${CVA6_REPO_DIR}/src/common_cells/include/
+incdir+${CVA6_REPO_DIR}/src/util/
${CVA6_REPO_DIR}/include/riscv_pkg.sv
${CVA6_REPO_DIR}/src/riscv-dbg/src/dm_pkg.sv
${CVA6_REPO_DIR}/include/ariane_pkg.sv
${CVA6_REPO_DIR}/src/common_cells/src/deprecated/rrarbiter.sv
${CVA6_REPO_DIR}/src/common_cells/src/deprecated/fifo_v1.sv
${CVA6_REPO_DIR}/src/common_cells/src/deprecated/fifo_v2.sv
${CVA6_REPO_DIR}/src/common_cells/src/fifo_v3.sv
${CVA6_REPO_DIR}/src/common_cells/src/lfsr_8bit.sv
${CVA6_REPO_DIR}/src/common_cells/src/lzc.sv
${CVA6_REPO_DIR}/src/common_cells/src/rr_arb_tree.sv
${CVA6_REPO_DIR}/src/common_cells/src/rstgen_bypass.sv
${CVA6_REPO_DIR}/src/common_cells/src/cdc_2phase.sv
${CVA6_REPO_DIR}/src/common_cells/src/shift_reg.sv
${CVA6_REPO_DIR}/src/common_cells/src/unread.sv
${CVA6_REPO_DIR}/src/common_cells/src/popcount.sv
${CVA6_REPO_DIR}/src/common_cells/src/exp_backoff.sv
${CVA6_REPO_DIR}/src/register_interface/src/apb_to_reg.sv
${CVA6_REPO_DIR}/src/register_interface/src/reg_intf_pkg.sv
${CVA6_REPO_DIR}/src/register_interface/src/reg_intf.sv
${CVA6_REPO_DIR}/src/fpu/src/fpnew_pkg.sv
${CVA6_REPO_DIR}/src/fpu/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv
${CVA6_REPO_DIR}/src/fpu/src/fpu_div_sqrt_mvp/hdl/control_mvp.sv
${CVA6_REPO_DIR}/src/fpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_mvp_wrapper.sv
${CVA6_REPO_DIR}/src/fpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv
${CVA6_REPO_DIR}/src/fpu/src/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv
${CVA6_REPO_DIR}/src/fpu/src/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv
${CVA6_REPO_DIR}/src/fpu/src/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv
${CVA6_REPO_DIR}/src/fpu/src/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv
${CVA6_REPO_DIR}/src/fpu/src/fpnew_cast_multi.sv
${CVA6_REPO_DIR}/src/fpu/src/fpnew_classifier.sv
${CVA6_REPO_DIR}/src/fpu/src/fpnew_divsqrt_multi.sv
${CVA6_REPO_DIR}/src/fpu/src/fpnew_fma_multi.sv
${CVA6_REPO_DIR}/src/fpu/src/fpnew_fma.sv
${CVA6_REPO_DIR}/src/fpu/src/fpnew_noncomp.sv
${CVA6_REPO_DIR}/src/fpu/src/fpnew_opgroup_block.sv
${CVA6_REPO_DIR}/src/fpu/src/fpnew_opgroup_fmt_slice.sv
${CVA6_REPO_DIR}/src/fpu/src/fpnew_opgroup_multifmt_slice.sv
${CVA6_REPO_DIR}/src/fpu/src/fpnew_rounding.sv
${CVA6_REPO_DIR}/src/fpu/src/fpnew_top.sv
${CVA6_REPO_DIR}/src/axi/src/axi_pkg.sv
${CVA6_REPO_DIR}/tb/ariane_soc_pkg.sv
${CVA6_REPO_DIR}/include/ariane_axi_pkg.sv
${CVA6_REPO_DIR}/include/wt_cache_pkg.sv
${CVA6_REPO_DIR}/include/std_cache_pkg.sv
${CVA6_REPO_DIR}/include/axi_intf.sv
${CVA6_REPO_DIR}/include/instr_tracer_pkg.sv
${CVA6_REPO_DIR}/src/util/instr_tracer_if.sv
${CVA6_REPO_DIR}/src/util/instr_tracer.sv
${CVA6_REPO_DIR}/src/util/sram.sv
${CVA6_REPO_DIR}/src/util/axi_master_connect.sv
${CVA6_REPO_DIR}/src/util/axi_master_connect_rev.sv
${CVA6_REPO_DIR}/src/util/axi_slave_connect.sv
${CVA6_REPO_DIR}/src/util/axi_slave_connect_rev.sv
${CVA6_REPO_DIR}/src/fpga-support/rtl/SyncSpRamBeNx64.sv
${CVA6_REPO_DIR}/src/axi_mem_if/src/axi2mem.sv
${CVA6_REPO_DIR}/src/tech_cells_generic/src/pulp_clock_gating.sv
${CVA6_REPO_DIR}/src/tech_cells_generic/src/cluster_clock_inverter.sv
${CVA6_REPO_DIR}/src/tech_cells_generic/src/pulp_clock_mux2.sv
${CVA6_REPO_DIR}/src/axi_adapter.sv
${CVA6_REPO_DIR}/src/alu.sv
${CVA6_REPO_DIR}/src/fpu_wrap.sv
${CVA6_REPO_DIR}/src/ariane.sv
${CVA6_REPO_DIR}/src/branch_unit.sv
${CVA6_REPO_DIR}/src/compressed_decoder.sv
${CVA6_REPO_DIR}/src/controller.sv
${CVA6_REPO_DIR}/src/csr_buffer.sv
${CVA6_REPO_DIR}/src/csr_regfile.sv
${CVA6_REPO_DIR}/src/decoder.sv
${CVA6_REPO_DIR}/src/ex_stage.sv
${CVA6_REPO_DIR}/src/instr_realign.sv
${CVA6_REPO_DIR}/src/frontend/btb.sv
${CVA6_REPO_DIR}/src/frontend/bht.sv
${CVA6_REPO_DIR}/src/frontend/ras.sv
${CVA6_REPO_DIR}/src/frontend/instr_scan.sv
${CVA6_REPO_DIR}/src/frontend/instr_queue.sv
${CVA6_REPO_DIR}/src/frontend/frontend.sv
${CVA6_REPO_DIR}/src/id_stage.sv
${CVA6_REPO_DIR}/src/issue_read_operands.sv
${CVA6_REPO_DIR}/src/issue_stage.sv
${CVA6_REPO_DIR}/src/load_unit.sv
${CVA6_REPO_DIR}/src/load_store_unit.sv
${CVA6_REPO_DIR}/src/mmu.sv
${CVA6_REPO_DIR}/src/mult.sv
${CVA6_REPO_DIR}/src/multiplier.sv
${CVA6_REPO_DIR}/src/serdiv.sv
${CVA6_REPO_DIR}/src/perf_counters.sv
${CVA6_REPO_DIR}/src/ptw.sv
${CVA6_REPO_DIR}/src/ariane_regfile_ff.sv
${CVA6_REPO_DIR}/src/re_name.sv
${CVA6_REPO_DIR}/src/scoreboard.sv
${CVA6_REPO_DIR}/src/store_buffer.sv
${CVA6_REPO_DIR}/src/amo_buffer.sv
${CVA6_REPO_DIR}/src/store_unit.sv
${CVA6_REPO_DIR}/src/tlb.sv
${CVA6_REPO_DIR}/src/commit_stage.sv
${CVA6_REPO_DIR}/src/cache_subsystem/wt_dcache_ctrl.sv
${CVA6_REPO_DIR}/src/cache_subsystem/wt_dcache_mem.sv
${CVA6_REPO_DIR}/src/cache_subsystem/wt_dcache_missunit.sv
${CVA6_REPO_DIR}/src/cache_subsystem/wt_dcache_wbuffer.sv
${CVA6_REPO_DIR}/src/cache_subsystem/wt_dcache.sv
${CVA6_REPO_DIR}/src/cache_subsystem/wt_icache.sv
${CVA6_REPO_DIR}/src/cache_subsystem/wt_l15_adapter.sv
${CVA6_REPO_DIR}/src/cache_subsystem/wt_cache_subsystem.sv
${CVA6_REPO_DIR}/src/clint/clint.sv
${CVA6_REPO_DIR}/src/clint/axi_lite_interface.sv
${CVA6_REPO_DIR}/src/riscv-dbg/src/dm_csrs.sv
${CVA6_REPO_DIR}/src/riscv-dbg/src/dm_mem.sv
${CVA6_REPO_DIR}/src/riscv-dbg/src/dm_top.sv
${CVA6_REPO_DIR}/src/riscv-dbg/src/dmi_cdc.sv
${CVA6_REPO_DIR}/src/riscv-dbg/src/dmi_jtag.sv
${CVA6_REPO_DIR}/src/riscv-dbg/src/dm_sba.sv
${CVA6_REPO_DIR}/src/riscv-dbg/src/dmi_jtag_tap.sv
${CVA6_REPO_DIR}/src/riscv-dbg/debug_rom/debug_rom.sv
${CVA6_REPO_DIR}/openpiton/ariane_verilog_wrap.sv
${CVA6_REPO_DIR}/openpiton/riscv_peripherals.sv
${CVA6_REPO_DIR}/openpiton/bootrom/baremetal/bootrom.sv
${CVA6_REPO_DIR}/openpiton/bootrom/linux/bootrom_linux.sv
${CVA6_REPO_DIR}/src/rv_plic/rtl/rv_plic_target.sv
${CVA6_REPO_DIR}/src/rv_plic/rtl/rv_plic_gateway.sv
${CVA6_REPO_DIR}/src/rv_plic/rtl/plic_regmap.sv
${CVA6_REPO_DIR}/src/rv_plic/rtl/plic_top.sv
${CVA6_REPO_DIR}/fpga/src/axi2apb/src/axi2apb_wrap.sv
${CVA6_REPO_DIR}/fpga/src/axi2apb/src/axi2apb.sv
${CVA6_REPO_DIR}/fpga/src/axi2apb/src/axi2apb_64_32.sv
${CVA6_REPO_DIR}/fpga/src/axi_slice/src/axi_w_buffer.sv
${CVA6_REPO_DIR}/fpga/src/axi_slice/src/axi_b_buffer.sv
${CVA6_REPO_DIR}/fpga/src/axi_slice/src/axi_slice_wrap.sv
${CVA6_REPO_DIR}/fpga/src/axi_slice/src/axi_slice.sv
${CVA6_REPO_DIR}/fpga/src/axi_slice/src/axi_single_slice.sv
${CVA6_REPO_DIR}/fpga/src/axi_slice/src/axi_ar_buffer.sv
${CVA6_REPO_DIR}/fpga/src/axi_slice/src/axi_r_buffer.sv
${CVA6_REPO_DIR}/fpga/src/axi_slice/src/axi_aw_buffer.sv
